#!/bin/bash

ruta_ejecucion=$(dirname "$(readlink -f "$0")")

#colores
rojo="\e[0;31m\033[1m" #rojo
verde="\e[;32m\033[1m"
azul="\e[0;34m\033[1m"
amarillo="\e[0;33m\033[1m"
rosa="\e[0;35m\033[1m"
turquesa="\e[0;36m\033[1m"
borra_colores="\033[0m\e[0m" #borra colores

#toma el control al pulsar control + c
trap ctrl_c INT
function ctrl_c()
{
clear
figlet -c Gracias por
figlet -c utilizar mi
figlet -c script
#wmctrl -r :ACTIVE: -b remove,maximized_vert,maximized_horz
exit
}


menu_info(){
#muestra el menu de sukigsx
echo ""
echo -e "${rosa}            _    _                  ${azul}   Nombre del script${borra_colores} (Instalacion de software)"
echo -e "${rosa}  ___ _   _| | _(_) __ _ _____  __  ${azul}   Descripcion${borra_colores} (Software de instalacion basado en Debian)"
echo -e "${rosa} / __| | | | |/ / |/ _\ / __\ \/ /  ${azul}   Version            =${borra_colores} $version"
echo -e "${rosa} \__ \ |_| |   <| | (_| \__ \>  <   ${azul}   Conexion Internet  =${borra_colores} $conexion"
echo -e "${rosa} |___/\__,_|_|\_\_|\__, |___/_/\_\  ${azul}   Software necesario =${borra_colores} $software"
echo -e "${rosa}                  |___/             ${azul}   Actualizado        =${borra_colores} $actualizado"
echo -e ""
echo -e "${azul} Contacto:${borra_colores} (Correo scripts@mbbsistemas.com) (Web https://repositorio.mbbsistemas.es)${borra_colores}"
echo ""
echo -e " ${verde} - INSTALACION AUDIO VIDEO -${borra_colores}"
echo ""
}

while :
do
    clear
    menu_info
    echo -e " Instalacion de software Audio-Video       Descripcion."
    echo -e ""
    echo -e "${azul}  1)${borra_colores} Vlc             Reproductor de todo."
    echo -e "${azul}  2)${borra_colores} Spotify         Plataforma de musica, requiere snap."
    echo -e "${azul}  3)${borra_colores} Digikam         Organizador de imagenes y editor de etiquetas"
    echo -e "${azul}  4)${borra_colores} Simple scan     Software para tu scaner"
    echo -e "${azul}  5)${borra_colores} Handbrake       Editor de video."
    echo -e "${azul}  6)${borra_colores} Shotwell        Organizador de imágenes."
    echo -e "${azul}  7)${borra_colores} Skanlite        Software para tu escaner."
    echo -e "${azul}  8)${borra_colores} krita           Es un estudio de arte digital completo."
    echo ""
    echo -e "${azul} 90)${borra_colores} Ayuda           Carga la ayuda"
    echo -e "${azul} 99)${borra_colores} Atras           Salir (ctrl-c)"
    echo -e ""
    read -p " Selcciona numero de categoria de software -> " opcion
        case $opcion in
            "1")#vlc
                #codigo para la instalacion se mete a /tmp/software
                echo "#vlc" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y vlc" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "vlc" >> /tmp/ComprobarSoftware
                echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                ;;

            "2")#spotify
                #codigo para la instalacion se mete a /tmp/software
                if extrepo search spotify; then
                    sudo extrepo enable spotify >/dev/null 2>&1
                    echo "#spotify" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "sudo apt update; sudo apt install -y spotify" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "spotify" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo "❌ No se encontró el repositorio para spotify."; read p
                fi
                ;;

            "3")#digukam
                #codigo para la instalacion se mete a /tmp/software
                echo "#digikam" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y digikam" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "digikam" >> /tmp/ComprobarSoftware
                echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                ;;

            "4")#Simple scan
                #codigo para la instalacion se mete a /tmp/software
                echo "#simple-scan" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y simple-scan" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "simple-scan" >> /tmp/ComprobarSoftware
                echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                ;;

            "5")#Handbrake
                #codigo para la instalacion se mete a /tmp/software
                echo "#handbrake" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y handbrake" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "handbrake" >> /tmp/ComprobarSoftware
                echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                ;;

            "6")#Shotwell
                #codigo para la instalacion se mete a /tmp/software
                echo "#shotwell" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y shotwell" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "shotwell" >> /tmp/ComprobarSoftware
                echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                ;;

            "7")#Skanlite
                #codigo para la instalacion se mete a /tmp/software
                echo "#skanlite" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y skanlite" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "skanlite" >> /tmp/ComprobarSoftware
                echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                ;;

            "8")#krita
                #codigo para la instalacion se mete a /tmp/software
                echo "#krita" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y krita" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "krita" >> /tmp/ComprobarSoftware
                echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                ;;

            "90")#carga la ayuda
                clear
                cat $ruta_ejecucion/AyudaInstalacionSoftware
                read pause
                ;;

            "99")#salir
                ctrl_c
                ;;

            *)#seleccion invalida
                echo -e ""
                echo -e "${amarillo} No has seleccionado una opcion valida del menu.${borra_colores}"
                sleep 3
                ;;
        esac
    done



