#!/bin/bash

ruta_ejecucion=$(dirname "$(readlink -f "$0")")

#colores
rojo="\e[0;31m\033[1m" #rojo
verde="\e[;32m\033[1m"
azul="\e[0;34m\033[1m"
amarillo="\e[0;33m\033[1m"
rosa="\e[0;35m\033[1m"
turquesa="\e[0;36m\033[1m"
borra_colores="\033[0m\e[0m" #borra colores

#toma el control al pulsar control + c
trap ctrl_c INT
function ctrl_c()
{
clear
figlet -c Gracias por
figlet -c utilizar mi
figlet -c script
#wmctrl -r :ACTIVE: -b remove,maximized_vert,maximized_horz
exit
}

menu_info(){
#muestra el menu de sukigsx
echo ""
echo -e "${rosa}            _    _                  ${azul}   Nombre del script${borra_colores} (Instalacion de software)"
echo -e "${rosa}  ___ _   _| | _(_) __ _ _____  __  ${azul}   Descripcion${borra_colores} (Software de instalacion basado en Debian)"
echo -e "${rosa} / __| | | | |/ / |/ _\ / __\ \/ /  ${azul}   Version            =${borra_colores} $version"
echo -e "${rosa} \__ \ |_| |   <| | (_| \__ \>  <   ${azul}   Conexion Internet  =${borra_colores} $conexion"
echo -e "${rosa} |___/\__,_|_|\_\_|\__, |___/_/\_\  ${azul}   Software necesario =${borra_colores} $software"
echo -e "${rosa}                  |___/             ${azul}   Actualizado        =${borra_colores} $actualizado"
echo -e ""
echo -e "${azul} Contacto:${borra_colores} (Correo scripts@mbbsistemas.com) (Web https://repositorio.mbbsistemas.es)${borra_colores}"
echo ""
echo -e " ${verde} - INSTALACION PAQUETES DE NAVEGADORES -${borra_colores}"
echo ""
}

while :
do
    clear
    menu_info
    echo -e " Navegadores disponibles       Descripcion."
    echo -e ""
    echo -e "${azul}  1)${borra_colores} Google Chrome             Navegador para internet"
    echo -e "${azul}  2)${borra_colores} Chromium-browser          Navegador para internet"
    echo -e "${azul}  3)${borra_colores} Firefox                   Navegador para internet"
    echo -e "${azul}  4)${borra_colores} Opera                     Navegador para internet"
    echo -e "${azul}  5)${borra_colores} Brave                     Navegador para internet"
    echo -e "${azul}  6)${borra_colores} Vivaldi                   Navegador para internet"
    echo ""
    echo -e "${azul} 90)${borra_colores} Ayuda                     Carga la ayuda"
    echo -e "${azul} 99)${borra_colores} Atras                     Salir (ctrl-c)"
    echo -e ""
    read -p " Selcciona numero de categoria de software -> " opcion

        case $opcion in
            "1") #google-chrome
                echo "#google-chrome" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "rm /tmp/google* >/dev/null 2>&1" >> /tmp/software
                echo "cd /tmp" >> /tmp/software
                echo 'wget -P /tmp https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb' >> /tmp/software
                echo 'sudo gdebi /tmp/google-chrome-stable_current_amd64.deb -n' >> /tmp/software
                echo "rm /tmp/google-chrome-stable_current_amd64.deb" >> /tmp/software
                echo "" >> /tmp/software
                echo "google-chrome-stable" >> /tmp/ComprobarSoftware
                echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                ;;

            "2") #chromium
                #codigo para la instalacion se mete a /tmp/software
                echo "#chromium-browser" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y chromium" >> /tmp/software
                echo "sudo apt install -y chromium-l10n" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "chromium" >> /tmp/ComprobarSoftware
                echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                ;;

            "3") #firefox
                #codigo para la instalacion se mete a /tmp/software
                echo "#firefox" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo "sudo apt install -y firefox-esr" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "firefox" >> /tmp/ComprobarSoftware
                echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                ;;

            "4") #opera
                #codigo para la instalacion se mete a /tmp/software
                echo "#opera" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo 'wget -qO- https://deb.opera.com/archive.key | sudo gpg --dearmor --yes -o /usr/share/keyrings/opera.gpg' >> /tmp/software
                echo 'echo "deb [signed-by=/usr/share/keyrings/opera.gpg] https://deb.opera.com/opera-stable/ stable non-free" | sudo tee /etc/apt/sources.list.d/opera-stable.list' >> /tmp/software
                echo "sudo apt update; sudo DEBIAN_FRONTEND=noninteractive apt install -y opera-stable"  >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "opera" >> /tmp/ComprobarSoftware
                echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                ;;

            "5") #brave
                #codigo para la instalacion se mete a /tmp/software
                echo "#brave" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo 'sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg' >> /tmp/software
                echo 'sudo curl -fsSLo /etc/apt/sources.list.d/brave-browser-release.sources https://brave-browser-apt-release.s3.brave.com/brave-browser.sources' >> /tmp/software
                echo "sudo apt update; sudo apt install -y brave-browser" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "brave-browser" >> /tmp/ComprobarSoftware
                echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                ;;

            "6") #vivaldi
                #codigo para la instalacion se mete a /tmp/software
                echo "#vivaldi" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                echo 'latest_version_url=$(curl -s https://vivaldi.com/download/ | grep -o 'https://downloads.vivaldi.com/stable/vivaldi-stable_[0-9\.]*-1_amd64.deb' | head -n 1)' >> /tmp/software
                echo 'curl -O "$latest_version_url"' >> /tmp/software
                echo "sudo gdebi vivaldi-stable*.deb -n" >> /tmp/software
                echo "rm vivaldi-stable*.deb" >> /tmp/software
                echo "" >> /tmp/software

                #linea con el nombre del programa instalado para la comprobacion
                echo "vivaldi-stable" >> /tmp/ComprobarSoftware
                echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                ;;

            "90") #Ayuda
                clear
                cat $ruta_ejecucion/AyudaInstalacionSoftware
                read pause
                ;;

            "99") #Salir
                ctrl_c
                ;;

            *) #seleccion invalida
                echo -e ""
                echo -e "${amarillo} No has seleccionado una opcion valida del menu.${borra_colores}"
                sleep 3
                ;;
        esac
    done

