#!/bin/bash
ruta_ejecucion=$(dirname "$(readlink -f "$0")")

#colores
rojo="\e[0;31m\033[1m" #rojo
verde="\e[;32m\033[1m"
azul="\e[0;34m\033[1m"
amarillo="\e[0;33m\033[1m"
rosa="\e[0;35m\033[1m"
turquesa="\e[0;36m\033[1m"
borra_colores="\033[0m\e[0m" #borra colores

#toma el control al pulsar control + c
trap ctrl_c INT
function ctrl_c()
{
clear
echo ""
echo -e "${azul} GRACIAS POR UTILIZAR MI SCRIPT${borra_colores}"
echo ""
sleep 1
exit
}
menu_info(){
#muestra el menu de sukigsx
echo ""
echo -e "${rosa}            _    _                  ${azul}   Nombre del script${borra_colores} $NombreScript"
echo -e "${rosa}  ___ _   _| | _(_) __ _ _____  __  ${azul}   Descripcion${borra_colores} $DescripcionDelScript"
echo -e "${rosa} / __| | | | |/ / |/ _\ / __\ \/ /  ${azul}   Version            =${borra_colores} $version"
echo -e "${rosa} \__ \ |_| |   <| | (_| \__ \>  <   ${azul}   Conexion Internet  =${borra_colores} $conexion"
echo -e "${rosa} |___/\__,_|_|\_\_|\__, |___/_/\_\  ${azul}   Software necesario =${borra_colores} $software"
echo -e "${rosa}                  |___/             ${azul}   Actualizado        =${borra_colores} $actualizado"
echo -e "${rosa}                                    ${azul}   Sistema paqueteria =${borra_colores} $paqueteria"
echo -e ""
echo -e "${azul} Contacto:${borra_colores} ( Correo${rosa} $Correo${borra_colores} ) ( Web${rosa} $Web${borra_colores} )${borra_colores}"
echo ""
echo -e " ${verde} - INSTALACION DE ENTORNOS GRAFICOS -${borra_colores}"
echo ""
}



while :
do
    clear
    menu_info
    echo -e " Navegadores disponibles       Descripcion."
    echo -e ""
    echo -e "${azul}  1)${borra_colores} Gnome                    Entorno grafico de Gnome."
    echo -e "${azul}  2)${borra_colores} Plasma                   Entorno grafico Plasma."
    echo -e "${azul}  3)${borra_colores} Cinnamon                 Entorno grafico Cinnamon."
    echo -e "${azul}  4)${borra_colores} Xfce4                    Entorno grafico Xfce."
    echo -e "${azul}  5)${borra_colores} Mate                     Entorno grafico Mate."
    echo -e "${azul}  6)${borra_colores} Lxde                     Entorno grafico Lxde."
    echo ""
    echo -e "${azul} 90)${borra_colores} Ayuda                    Carga la ayuda"
    echo -e "${azul} 99)${borra_colores} Atras                    Salir (ctrl-c)"
    echo -e ""
    read -p " Selcciona numero de categoria de software -> " opcion

        case $opcion in
            "1")#gnome
                nombre_paquete="gnome"
                nombre_paquete_comprobar="gnome"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "2")#plasma
                nombre_paquete="plasma"
                nombre_paquete_comprobar="plasma"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete kde-applications" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "3")#Cinnamon
                nombre_paquete="cinnamon"
                nombre_paquete_comprobar="cinnamon"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "4")#xfce4
                nombre_paquete="xfce4"
                nombre_paquete_comprobar="xfce4"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete xfce4-goodies" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "5")#mate
                nombre_paquete="mate"
                nombre_paquete_comprobar="mate"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete mate-extre" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "6")#lxde
                nombre_paquete="lxde"
                nombre_paquete_comprobar="lxde"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "90") #Ayuda
                clear
                cat $ruta_ejecucion/AyudaInstalacionSoftware
                read pause
                ;;

            "99") #Salir
                ctrl_c
                ;;


            *) #seleccion invalida
                echo -e ""
                echo -e "${amarillo} No has seleccionado una opcion valida del menu.${borra_colores}"
                sleep 3
                ;;
        esac
    done
