#!/bin/bash

ruta_ejecucion=$(dirname "$(readlink -f "$0")")

#colores
rojo="\e[0;31m\033[1m" #rojo
verde="\e[;32m\033[1m"
azul="\e[0;34m\033[1m"
amarillo="\e[0;33m\033[1m"
rosa="\e[0;35m\033[1m"
turquesa="\e[0;36m\033[1m"
borra_colores="\033[0m\e[0m" #borra colores

#toma el control al pulsar control + c
trap ctrl_c INT
function ctrl_c()
{
clear
echo ""
echo -e "${azul} GRACIAS POR UTILIZAR MI SCRIPT${borra_colores}"
echo ""
sleep 1
exit
}


menu_info(){
#muestra el menu de sukigsx
echo ""
echo -e "${rosa}            _    _                  ${azul}   Nombre del script${borra_colores} $NombreScript"
echo -e "${rosa}  ___ _   _| | _(_) __ _ _____  __  ${azul}   Descripcion${borra_colores} $DescripcionDelScript"
echo -e "${rosa} / __| | | | |/ / |/ _\ / __\ \/ /  ${azul}   Version            =${borra_colores} $version"
echo -e "${rosa} \__ \ |_| |   <| | (_| \__ \>  <   ${azul}   Conexion Internet  =${borra_colores} $conexion"
echo -e "${rosa} |___/\__,_|_|\_\_|\__, |___/_/\_\  ${azul}   Software necesario =${borra_colores} $software"
echo -e "${rosa}                  |___/             ${azul}   Actualizado        =${borra_colores} $actualizado"
echo -e "${rosa}                                    ${azul}   Sistema paqueteria =${borra_colores} $paqueteria"
echo -e ""
echo -e "${azul} Contacto:${borra_colores} ( Correo${rosa} $Correo${borra_colores} ) ( Web${rosa} $Web${borra_colores} )${borra_colores}"
echo ""
echo -e " ${verde} - INSTALACION AUDIO VIDEO -${borra_colores}"
echo ""
}

while :
do
    clear
    menu_info
    echo -e " Instalacion de software Imagen-Audio-Video       Descripcion."
    echo -e ""
    echo -e "${azul}   1)${borra_colores} Vlc             Reproductor de todo."
    echo -e "${azul}   2)${borra_colores} Spotify         Plataforma de musica."
    echo -e "${azul}   3)${borra_colores} Digikam         Organizador de imagenes y editor de etiquetas"
    echo -e "${azul}   4)${borra_colores} Simple scan     Software para tu scaner"
    echo -e "${azul}   5)${borra_colores} Handbrake       Editor de video."
    echo -e "${azul}   6)${borra_colores} Shotwell        Organizador de imágenes."
    echo -e "${azul}   7)${borra_colores} Skanlite        Software para tu escaner."
    echo -e "${azul}   8)${borra_colores} Krita           Es un estudio de arte digital completo."
    echo -e "${azul}   9)${borra_colores} Freetube        Reproductor de videos de youtube Sin anuncios."
    echo -e "${azul}  10)${borra_colores} HarmonyMusic    Reproductor de musica online sin anuncion."
    echo ""
    echo -e "${azul} 90)${borra_colores} Ayuda           Carga la ayuda"
    echo -e "${azul} 99)${borra_colores} Atras           Salir (ctrl-c)"
    echo -e ""
    read -p " Selcciona numero de categoria de software -> " opcion
        case $opcion in
            "1")#vlc
                nombre_paquete="vlc"
                nombre_paquete_comprobar="vlc"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "2")#spotify
                nombre_paquete="spotify"
                nombre_paquete_comprobar="spotify"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "3")#Digikam
                nombre_paquete="digikam"
                nombre_paquete_comprobar="digikam"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "4")#Simple scan
               nombre_paquete="simple-scan"
                nombre_paquete_comprobar="simple-scan"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "5")#Handbrake
                #codigo para la instalacion se mete a /tmp/software
                nombre_paquete="handbrake"
                nombre_paquete_comprobar="handbrake"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "6")#Shotwell
                nombre_paquete="shotwell"
                nombre_paquete_comprobar="shotwell"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "7")#Skanlite
                nombre_paquete="skanlite"
                nombre_paquete_comprobar="skanlite"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "8")#krita
                nombre_paquete="krita"
                nombre_paquete_comprobar="krita"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "9")#freetube
                nombre_paquete="freetube"
                nombre_paquete_comprobar="freetube"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "10")#harmonymusic
                nombre_paquete="harmonymusic"
                nombre_paquete_comprobar="harmonymusic"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;


            "90")#carga la ayuda
                clear
                cat $ruta_ejecucion/AyudaInstalacionSoftware
                read pause
                ;;

            "99")#salir
                ctrl_c
                ;;

            *)#seleccion invalida
                echo -e ""
                echo -e "${amarillo} No has seleccionado una opcion valida del menu.${borra_colores}"
                sleep 3
                ;;
        esac
    done



