#!/bin/bash
ruta_ejecucion=$(dirname "$(readlink -f "$0")")

#colores
rojo="\e[0;31m\033[1m" #rojo
verde="\e[;32m\033[1m"
azul="\e[0;34m\033[1m"
amarillo="\e[0;33m\033[1m"
rosa="\e[0;35m\033[1m"
turquesa="\e[0;36m\033[1m"
borra_colores="\033[0m\e[0m" #borra colores

#toma el control al pulsar control + c
trap ctrl_c INT
function ctrl_c()
{
clear
exit
}

menu_info(){
#muestra el menu de sukigsx
echo ""
echo -e "${rosa}            _    _                  ${azul}   Nombre del script${borra_colores} $NombreScript"
echo -e "${rosa}  ___ _   _| | _(_) __ _ _____  __  ${azul}   Descripcion${borra_colores} $DescripcionDelScript"
echo -e "${rosa} / __| | | | |/ / |/ _\ / __\ \/ /  ${azul}   Version            =${borra_colores} $version"
echo -e "${rosa} \__ \ |_| |   <| | (_| \__ \>  <   ${azul}   Conexion Internet  =${borra_colores} $conexion"
echo -e "${rosa} |___/\__,_|_|\_\_|\__, |___/_/\_\  ${azul}   Software necesario =${borra_colores} $software"
echo -e "${rosa}                  |___/             ${azul}   Actualizado        =${borra_colores} $actualizado"
echo -e "${rosa}                                    ${azul}   Sistema paqueteria =${borra_colores} $paqueteria"
echo -e ""
echo -e "${azul} Contacto:${borra_colores} ( Correo${rosa} $Correo${borra_colores} ) ( Web${rosa} $Web${borra_colores} )${borra_colores}"
echo ""
echo -e " ${verde} - INSTALACION PAQUETES DE UTILIDADES -${borra_colores}"
echo ""
}


while :
do
    clear
    menu_info
    echo -e " Navegadores disponibles       Descripcion."
    echo -e ""
    echo -e "${azul}  1)${borra_colores} Grub-customizer                   Modifica el gestor de arranque."
    echo -e "${azul}  2)${borra_colores} Cairo-Dock                        Crear paneles y lanzadores, muy personalizados."
    echo -e "${azul}  3)${borra_colores} Opcion vacia                      Opcion para nuevas utilidades"
    echo -e "${azul}  4)${borra_colores} Tellico                           Crea tu base de datos de cd dvd libros etc."
    echo -e "${azul}  5)${borra_colores} KDE Connect                       Sincroniza tu movil con el pc."
    echo -e "${azul}  6)${borra_colores} Usuarios y Grupos                 Gestiona Usuarios y Grupos de modo grafico."
    echo -e "${azul}  7)${borra_colores} Gnome-online-accouns              Para poder sincronizar cuentas de google (drive)."
    echo -e "${azul}  8)${borra_colores} Kio gdrive                        Para poder sincronizar cuentas de google (drive) solo entornos KDE Plasma."
    echo -e "${azul}  9)${borra_colores} Ocamlfuse (<debian13)             Otro para poder sincronizar cuentas de google (drive)."
    echo -e "${azul} 10)${borra_colores} Nemo                              Explorador de ficheos."
    echo -e "${azul} 11)${borra_colores} Systemback (<debian13)            Utilidades para gestionar el sistema."
    echo -e "${azul} 12)${borra_colores} Deja-dup                          Copia de seguridad de tus ficheros o sistema."
    echo -e "${azul} 13)${borra_colores} Transmision                       Gestor de descargas torrent."
    echo -e "${azul} 14)${borra_colores} Opcion vacia                      Opcion para nuevas utilidades"
    echo -e "${azul} 15)${borra_colores} Joplin                            Software multiplataforma para tomar notas."
    echo -e "${azul} 16)${borra_colores} Keepass                           Gestor de contraseñas."
    echo -e "${azul} 17)${borra_colores} Github Desktop                    Gestor grafico de Github."
    echo -e "${azul} 18)${borra_colores} Teamviwer                         Conexion remota."
    echo -e "${azul} 19)${borra_colores} RustDesk                          Conexion remota."
    echo -e "${azul} 20)${borra_colores} Stacer                            Monitorizar y optimizar tu sistema Linux."
    echo -e "${azul} 21)${borra_colores} Hidamari                          Herramienta para poner videos o webs como fondo pantalla."
    echo ""
    echo -e "${azul} 90)${borra_colores} Ayuda                     Carga la ayuda"
    echo -e "${azul} 99)${borra_colores} Atras                     Salir (ctrl-c)"
    echo -e ""
    read -p " Selcciona numero de categoria de software -> " opcion


    case $opcion in
            "1")#Grub-customizer
                nombre_paquete="Grub-customizer"
                nombre_paquete_comprobar="Grub-customizer"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "2")#Cairo-Dock
                nombre_paquete="cairo-dock"
                nombre_paquete_comprobar="cairo-dock"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "3")#opcion vacia
                echo ""
                 echo -e "${amarillo} Opcion vacia.${borra_colores}"
                 sleep 2
                 ;;
                ;;

            "4")#Tellico
                nombre_paquete="tellico"
                nombre_paquete_comprobar="tellico"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "5")#KDE Connect
                nombre_paquete="kdeconnect"
                nombre_paquete_comprobar="kdeconnect"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "6")#Usuarios y Grupos
                nombre_paquete="gnome-system-tools"
                nombre_paquete_comprobar="gnome-system-tools"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "7")#Gnome-online-accouns
                nombre_paquete="gnome-online-accounts"
                nombre_paquete_comprobar="gnome-online-accounts"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "8")#Kio gdrive
                nombre_paquete="kio-gdrive"
                nombre_paquete_comprobar="kioclient5"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete kaccounts-providers" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "9")#Ocamlfuse
               nombre_paquete="google-drive-ocamlfuse"
                nombre_paquete_comprobar="google-drive-ocamlfuse"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "10")#Nemo
               nombre_paquete="nemo"
                nombre_paquete_comprobar="nemo"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "11")#Systemback
                nombre_paquete="Systemback"
                nombre_paquete_comprobar="Systemback"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "12")#Deja-dup
                nombre_paquete="deja-dup"
                nombre_paquete_comprobar="deja-dup"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "13")#Transmision
                nombre_paquete="transmission-qt"
                nombre_paquete_comprobar="transmission-qt"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete transmission-gtk" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "14")#Software-propietario
                 echo ""
                 echo -e "${amarillo} Opcion vacia.${borra_colores}"
                 sleep 2
                 ;;

            "15")#Joplin
                nombre_paquete="joplin"
                nombre_paquete_comprobar="joplin"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "16")#Keepass
                nombre_paquete="keepass"
                nombre_paquete_comprobar="keepass"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "17")#GithubDesktop
                nombre_paquete="github-desktop"
                nombre_paquete_comprobar="github-desktop"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "18")#teamviewer
                nombre_paquete="teamviewer"
                nombre_paquete_comprobar="teamviewer"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

            "19")#rustdesk
                nombre_paquete="rustdesk"
                nombre_paquete_comprobar="rustdesk"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;

                "20")#Stacer
                    nombre_paquete="Stacer"
                    nombre_paquete_comprobar="Stacer"
                    if yay -Si "$nombre_paquete" &>/dev/null; then
                        #codigo para la instalacion se mete a /tmp/software
                        echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                        echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                        echo "" >> /tmp/software

                        #linea con el nombre del programa instalado para la comprobacion
                        echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                        echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                    else
                        echo ""
                        echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                        echo ""; sleep 4
                    fi
                    ;;

                "21")#Hidamari
                nombre_paquete="hidamari"
                nombre_paquete_comprobar="hidamari"
                if yay -Si "$nombre_paquete" &>/dev/null; then
                    #codigo para la instalacion se mete a /tmp/software
                    echo "#$nombre_paquete" >> /tmp/software #mete el nombre del programa para poder comprobar su instalacion
                    echo "yay -S --noconfirm $nombre_paquete" >> /tmp/software
                    echo "" >> /tmp/software

                    #linea con el nombre del programa instalado para la comprobacion
                    echo "$nombre_paquete_comprobar" >> /tmp/ComprobarSoftware
                    echo ""; echo -e "${azul} Añadido ${verde}OK${borra_colores}"; sleep 1
                else
                    echo ""
                    echo -e "${amarillo} El paquete ${borra_colores}$nombre_paquete${amarillo} NO existe en repositorios ni en AUR.${borra_colores}"
                    echo ""; sleep 4
                fi
                ;;


            "90")#carga la ayuda
                clear
                cat $ruta_ejecucion/AyudaInstalacionSoftware
                read pause
                ;;

            "90") #Ayuda
                clear
                cat $ruta_ejecucion/AyudaInstalacionSoftware
                read pause
                ;;

            "99") #Salir
                ctrl_c
                ;;

            *) #seleccion invalida
                echo -e ""
                echo -e "${amarillo} No has seleccionado una opcion valida del menu.${borra_colores}"
                sleep 3
                ;;
        esac
    done
